using System;
using Sifteo;

namespace CubeTyper
{
	public class Typer
	{

		public Typer ()
		{

		}
	


		public void printText(Cube cube, String text, int x, int y){
			int offset = 0;
			foreach(char c in text.ToLower().ToCharArray()){
				offset = offset + printChar(cube, c, x+offset, y);

			}
		}
		// draws a char to on the cube 
		// returns an int to tell how wide the char is
		public int printChar(Cube cube, char d, int cX, int cY){
			Color chr_clr = new Color (0, 0, 0);

			switch (d) {
			case 'a':

				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 8, 1, 1);
				return 9;
			case 'b':

				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);

				return 8;

			case 'c':

				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				return 8;
			case 'd':


				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 11, 1, 1);

				return 8;
			case 'e':

				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 6, 1, 1);
				return 9;
			case 'f':

				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				return 5;
			case 'g':

				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 10, 1, 1);
				return 8;
			case 'h':

				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 11, 1, 1);
				return 7;
			case 'i':

				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				return 2;
			case 'j':


				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 12, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 13, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 14, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 12, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 13, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 14, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 12, 1, 1);
				return 3;
			case 'k':


				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 11, 1, 1);
				return 8;
			case 'l':


				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				return 3;
			case 'm':

				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 10, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 10, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 10, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 10, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 10, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 10, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 10, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 10, cY + 8, 1, 1);

				return 11;
			case 'n':


				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				return 7;
			case 'o':


				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 6, 1, 1);
				return 9;
			case 'p':


				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 5, 1, 1);
				return 8;
			case 'q':


				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 11, 1, 1);
				return 8;
			case 'r':


				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				return 5;
			case 's':


				cube.FillRect(chr_clr, cX+0, cY+1, 1, 1);
				cube.FillRect(chr_clr, cX+0, cY+2, 1, 1);
				cube.FillRect(chr_clr, cX+0, cY+3, 1, 1);
				cube.FillRect(chr_clr, cX+0, cY+7, 1, 1);
				cube.FillRect(chr_clr, cX+1, cY+0, 1, 1);
				cube.FillRect(chr_clr, cX+1, cY+1, 1, 1);
				cube.FillRect(chr_clr, cX+1, cY+2, 1, 1);
				cube.FillRect(chr_clr, cX+1, cY+3, 1, 1);
				cube.FillRect(chr_clr, cX+1, cY+7, 1, 1);
				cube.FillRect(chr_clr, cX+1, cY+8, 1, 1);
				cube.FillRect(chr_clr, cX+2, cY+0, 1, 1);
				cube.FillRect(chr_clr, cX+2, cY+1, 1, 1);
				cube.FillRect(chr_clr, cX+2, cY+3, 1, 1);
				cube.FillRect(chr_clr, cX+2, cY+4, 1, 1);
				cube.FillRect(chr_clr, cX+2, cY+7, 1, 1);
				cube.FillRect(chr_clr, cX+2, cY+8, 1, 1);
				cube.FillRect(chr_clr, cX+3, cY+0, 1, 1);
				cube.FillRect(chr_clr, cX+3, cY+3, 1, 1);
				cube.FillRect(chr_clr, cX+3, cY+4, 1, 1);
				cube.FillRect(chr_clr, cX+3, cY+8, 1, 1);
				cube.FillRect(chr_clr, cX+4, cY+0, 1, 1);
				cube.FillRect(chr_clr, cX+4, cY+4, 1, 1);
				cube.FillRect(chr_clr, cX+4, cY+8, 1, 1);
				cube.FillRect(chr_clr, cX+5, cY+0, 1, 1);
				cube.FillRect(chr_clr, cX+5, cY+1, 1, 1);
				cube.FillRect(chr_clr, cX+5, cY+4, 1, 1);
				cube.FillRect(chr_clr, cX+5, cY+5, 1, 1);
				cube.FillRect(chr_clr, cX+5, cY+6, 1, 1);
				cube.FillRect(chr_clr, cX+5, cY+7, 1, 1);
				cube.FillRect(chr_clr, cX+5, cY+8, 1, 1);
				cube.FillRect(chr_clr, cX+6, cY+1, 1, 1);
				cube.FillRect(chr_clr, cX+6, cY+4, 1, 1);
				cube.FillRect(chr_clr, cX+6, cY+5, 1, 1);
				cube.FillRect(chr_clr, cX+6, cY+6, 1, 1);
				cube.FillRect(chr_clr, cX+6, cY+7, 1, 1);
				cube.FillRect(chr_clr, cX+6, cY+8, 1, 1);
				cube.FillRect(chr_clr, cX+7, cY+5, 1, 1);
				cube.FillRect(chr_clr, cX+7, cY+6, 1, 1);
				cube.FillRect(chr_clr, cX+7, cY+7, 1, 1);
				return 8;
			case 't':

				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				return 4;
			case 'u':
			

				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				return 7;
			case 'v':


				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				return 7;
			case 'w':

				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 9, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 10, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 10, cY + 1, 1, 1);
				return 11;
			case 'x':


				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				return 7;
			case 'y':

				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 1, 1, 1);
				return 9;
			case 'z':


				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				return 8;

			case '0':


				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 9, 1, 1);

				return 9;

			case '1':

				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);

				return 5;

			case '2':


				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 11, 1, 1);

				return 9;

			case '3':
			

				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 9, 1, 1);
				return 9;

			case '4':

				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 8, 1, 1);

				return 9;
			case '5':

				cube.FillRect (chr_clr, cX + 0, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);

				return 8;
			case '6':


				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 8, 1, 1);

				return 9;
			case '7':

				cube.FillRect (chr_clr, cX + 0, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 0, 1, 1);

				return 9;
			case '8':


				cube.FillRect (chr_clr, cX + 0, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 9, 1, 1);

				return 9;
			case '9':


				cube.FillRect (chr_clr, cX + 0, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 0, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 1, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 2, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 3, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 4, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 5, cY + 11, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 0, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 6, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 1, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 2, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 7, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 8, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 9, 1, 1);
				cube.FillRect (chr_clr, cX + 7, cY + 10, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 3, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 4, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 5, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 6, 1, 1);
				cube.FillRect (chr_clr, cX + 8, cY + 7, 1, 1);

				return 9;
			
			}
			return 5;
		


		}

	}
}

